name: expand_widget
description: Ability to easily expand and retract a widget collection or text
version: 3.1.0
homepage: https://github.com/jesusrp98/expand_widget

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
